apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: host-data
        mountPath: /usr/share/nginx/html
  volumes:
  - name: host-data
    hostPath:
      path: /tmp/html