apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-exec
spec:
  containers:
  - name: readiness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 10; touch /tmp/ready; sleep 600
    readinessProbe:
      exec:
        command: ['sh', '-c', 'cat /tmp/ready']
      initialDelaySeconds: 15
      periodSeconds: 5
  terminationGracePeriodSeconds: 0