apiVersion: v1
kind: Pod
metadata:
  name: security-context-2
spec:
  containers:
  - name: sec-ctx-2
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]