apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      parallelism: 2
      completions: 6
      activeDeadlineSeconds: 100
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: pi
            image: perl
            command: ["perl"]
            args: 
            - -Mbignum=bpi
            - -wle
            - print bpi(2000)
          restartPolicy: Never
      backoffLimit: 4