apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
  - name: 1st
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: busybox
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "Kubernetes:" $(date) > /html/index.html;
          sleep 1;
        done
  volumes:
  - name: html
    emptyDir: {}