apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  clusterIP: None # <-- Don't forget!!
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80