apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: frontend
      labels:
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: nginx